import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import CarsList from '../components/CarsList';
import HeroSection from '../components/HeroSection';
import Navbar from '../components/navbar';
import Sidebar from '../components/Sidebar';
import styles from '../styles/Home.module.css';
import CostModal from '../components/CostModal';
import { FaExternalLinkAlt } from 'react-icons/fa';

export default function Home() {
  const [showModal, setShowModal] = useState(false);

  const ctaData = [
    {
      nombre: 'Città',
      percentuali: 33,
      color: '#FFC31F',
    },
    {
      nombre: 'Statale',
      percentuali: 33,
      color: '#3E97FF',
    },
    {
      nombre: 'Autostrada',
      percentuali: 33,
      color: '#26BE0A',
    },
  ];

  const carsData = [
    {
      name: 'VOLKSWAGEN ECO UP!',
      model: 'move 5 porte',
      type: 'Berlina',
      force: '150CV | 110kW',
      volume: '1395',
      image: 'https://preview2.netcarshow.com/Volkswagen-Eco_Up-2013-hd.jpg',
      fuel: 'GPL',
      costs: [
        {
          value: '3,85',
          extra: 'per le tue abitudini',
        },
      ],
    },
    {
      name: 'FORD FIESTA',
      model: '1.1 75 CV Gpl 5p.',
      type: 'Berlina',
      force: '150CV | 110kW',
      volume: '1395',
      image: 'https://preview2.netcarshow.com/Volkswagen-Eco_Up-2013-hd.jpg',
      fuel: 'GPL',
      costs: [{ value: '4,96' }],
    },
    {
      name: 'HYUNDAY IONIQ',
      model: 'ELECTRIC EV 38.3 kWhA',
      type: 'Berlina',
      force: '150CV | 110kW',
      image: 'https://preview2.netcarshow.com/Volkswagen-Eco_Up-2013-hd.jpg',
      fuel: 'ELECTRICA',
      costs: [
        { value: '3,40', extra: '- ricarica domestica' },
        { value: '8,54', extra: '- col. corrente continua' },
      ],
    },
    {
      name: 'TOYOTA PRIUS',
      model: 'Plug-in Hybrid',
      type: 'Berlina',
      force: '150CV | 110kW',
      image: 'https://preview2.netcarshow.com/Volkswagen-Eco_Up-2013-hd.jpg',
      fuel: 'PLUG-IN HYBRID',
      costs: [
        { value: '3,40', extra: 'ricarica domestica' },
        { value: '8,54', extra: 'col. cor. continua' },
      ],
    },
  ];

  const fuels = [
    { value: null, text: 'Tutte' },
    { value: 123, text: 'Benzina' },
    { value: 71, text: 'Gasolio' },
    { value: 5, text: 'Mild Hybrid Benzina' },
    { value: 15, text: 'Full Hybrid' },
    { value: 34, text: 'Plug-in Hybrid' },
    { value: 34, text: 'Electrica' },
    { value: 6, text: 'GPL' },
    { value: 6, text: 'Metano' },
  ];

  const types = [
    { value: null, text: 'Tutte' },
    { value: 2, text: 'Coupé' },
    { value: 1, text: 'City Car' },
    { value: 2, text: 'Station wagon' },
    { value: 1, text: 'Berlina' },
    { value: 2, text: 'Monovolume' },
    { value: 1, text: 'Cabrio' },
    { value: 2, text: 'Suv/Fuoristrada' },
  ];

  const companies = [
    { text: `Tutte` },
    { text: `Mahindra` },
    { text: `Alfa Romeo` },
    { text: `Mazda` },
    { text: `Alpine` },
    { text: `Mercedes` },
    { text: `Aston Martin` },
    { text: `Mg` },
    { text: `Audi` },
    { text: `Mini` },
    { text: `Bmw` },
    { text: `Mitsubishi` },
    { text: `Citroen` },
    { text: `Nissan` },
    { text: `Cupra` },
    { text: `Opel` },
    { text: `Dacia` },
    { text: `Peugeot` },
    { text: `Ds` },
    { text: `Porsche` },
    { text: `Dr` },
    { text: `Renault` },
    { text: `Fiat` },
    { text: `Seat` },
    { text: `Ford` },
    { text: `Skoda` },
    { text: `Honda` },
    { text: `Ssangyong` },
    { text: `Hyundai` },
    { text: `Subaru` },
    { text: `Jaguar` },
    { text: `Suzuki` },
    { text: `Jeep` },
    { text: `Toyota` },
    { text: `Kia` },
    { text: `Tesla` },
    { text: `Lancia` },
    { text: `Volkswagen` },
    { text: `Land Rover` },
    { text: `Volvo Xev` },
    { text: `Lexus` },
  ];

  return (
    <>
      <Head>
        <title>€x100km - Q Premium</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <header className='hero'>
        <HeroSection openModal={() => setShowModal(true)} ctaData={ctaData} />
      </header>

      <main className='container'>
        <Sidebar types={types} companies={companies} fuels={fuels} />
        <section className='cars'>
          <div
            className='desktop-order'
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'flex-end',
            }}
          >
            <span>Ordina per</span>
            <ul className='order'>
              <li className='selected'>Costa</li>
              <li>Potenza</li>
              <li>Cilindrata</li>
              <li>Marca</li>
            </ul>
          </div>
          <div className='mobile-order'>
            <div className='date'>
              <span className='date__icon'>
                <FaExternalLinkAlt />
              </span>
              <span className='date__text'>Info Prezzi</span>
            </div>
            <div className='select'>
              <span>Ordina per </span>
              <select className='order-selector'>
                <option selected value='costo'>
                  Costo
                </option>
                <option value='potenza'>Potenza</option>
                <option value='cilindrata'>Cilindrata</option>
                <option value='marca'>Marca</option>
              </select>
            </div>
          </div>
          <CarsList cars={carsData} />
        </section>
      </main>

      {showModal && (
        <CostModal closeModal={() => setShowModal(false)} ctaData={ctaData} />
      )}

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
}
